#spring:
#  datasource:
#    username: root
#    password: 456852
#    url: jdbc:mysql//localhost:3306/javatechie
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties: org.hibernate.dialect.MySQL5Dialect